# Generated by Django 3.1.2 on 2020-10-27 06:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paintings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer', models.CharField(blank=True, max_length=50)),
                ('designerId', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=400), default=list, size=None)),
                ('price', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
