# Generated by Django 3.1.2 on 2020-10-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintings',
            name='id',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
