# Generated by Django 3.1.2 on 2020-10-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0004_auto_20201027_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintings',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paintings',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
